services:
  frontend:
    build:
      context: ./alice_frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT_DOCKER}"
    depends_on:
      backend:
        condition: service_healthy
      workflow:
        condition: service_healthy
    volumes:
      # - ./alice_frontend:/app:delegated
      - /app/node_modules
    environment:
      NODE_ENV: production
      # CHOKIDAR_USEPOLLING: "true"
      # WATCHPACK_POLLING: "true"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT_DOCKER}"
    depends_on:
      mongo:
        condition: service_started
    volumes:
      - ./.env:/app/.env
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: production
    command: sh -c "npm run build && nodemon --watch src --ext ts --exec 'npm run build && node dist/index.js'"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT_DOCKER}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  mongo:
    image: mongo:latest
    ports:
      - "26017:27017"
    volumes:
      - mongo_data:/data/db

  workflow:
    build:
      context: ./workflow_logic
    ports:
      - "${WORKFLOW_PORT}:${WORKFLOW_PORT_DOCKER}"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock  # Add this line
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - PYTHONPATH=/app
      - HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${WORKFLOW_PORT_DOCKER}/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

volumes:
  mongo_data: