version: '3.8'

services:
  frontend:
    build:
      context: ./alice_frontend
      dockerfile: Dockerfile.dev
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT_DOCKER}"
    depends_on:
      - backend
      - workflow
    volumes:
      - ./alice_frontend:/app:delegated
      - /app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT_DOCKER}"
    depends_on:
      - mongo
    volumes:
      - ./.env:/app/.env
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  mongo:
    image: mongo:latest
    ports:
      - "26017:27017" 
    volumes:
      - mongo_data:/data/db

  workflow:
    build:
      context: ./workflow_logic
    ports:
      - "${WORKFLOW_PORT}:${WORKFLOW_PORT_DOCKER}"
    volumes:
      - .:/app
      - ${MODEL_FOLDER}:/models
    depends_on:
      - backend
    environment:
      - PYTHONPATH=/app
      - MODEL_FOLDER=/models
      - HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  mongo_data:
